Various minor bugfixes, cosmetics

diff --git a/DELETE_release b/DELETE_release
--- a/DELETE_release
+++ b/DELETE_release
@@ -83,6 +83,29 @@ if ( [ ${BASEPATH}Linux_i686_intel/devel -ef ${BASEPATH}Linux_i686_intel/${REL_N
      exit 1
 fi
 
+# Test requested release against all older devel and current links.
+# Don't delete if the requested release matches any of them.
+for j in ${BASEPATH}Linux_i686_intel/current*
+do
+  if ( [ ${j} -ef ${BASEPATH}Linux_i686_intel/${REL_NAME} ] ) then
+      echo ""
+      echo "The release you have requested to delete is an older CURRENT release."
+      echo "This is not currently allowed.  Aborting."
+      echo ""
+      exit 1
+  fi
+done
+
+for k in ${BASEPATH}Linux_i686_intel/devel*
+do
+  if ( [ ${k} -ef ${BASEPATH}Linux_i686_intel/${REL_NAME} ] ) then
+      echo ""
+      echo "The release you have requested to delete is an older DEVEL release."
+      echo "This is not currently allowed.  Aborting."
+      echo ""
+      exit 1
+  fi
+done
 
 
 echo ""
@@ -107,7 +130,7 @@ if ( [ ! ${CONFIRM} = "\n" ] ) then
     exit 1
 fi
 
-echo " @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
+echo -e " @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\a"
 echo " @                                                       @"
 echo " @ Hit  <CNTRL><C>  _NOW_ IF YOU DO NOT WANT TO DO THIS. @"
 echo " @                (You have 10 seconds)                  @"
