Protect against common command name redefinitions via alias by users

diff --git a/dist_source_me b/dist_source_me
--- a/dist_source_me
+++ b/dist_source_me
@@ -36,15 +36,15 @@
 # when/if it is sourced.  Otherwise, this describes the
 # failure that occurred prior to running the source step.
 #----------------------------------------------------------
-echo "" > ${HOME}/.dist_setup_log.tmp
-echo "Execution of distribution setup chain starting in dist_source_me failed." >> ${HOME}/.dist_setup_log.tmp
-echo "" >> ${HOME}/.dist_setup_log.tmp
-echo "Verify that the current working directory when running dist_source_me is the" >> ${HOME}/.dist_setup_log.tmp
-echo "top level directory of a distribution source tree -or- if running the script" >> ${HOME}/.dist_setup_log.tmp
-echo "from another location, that the value of the environment variable DIST_BASE_DIR"  >> ${HOME}/.dist_setup_log.tmp
-echo "contains the full path of the top-level directory of a distribution source tree AND has" >> ${HOME}/.dist_setup_log.tmp
-echo "been made available (exported) to child processes of your current shell." >> ${HOME}/.dist_setup_log.tmp
-echo "" >> ${HOME}/.dist_setup_log.tmp
+"echo" "" > ${HOME}/.dist_setup_log.tmp
+"echo" "Execution of distribution setup chain starting in dist_source_me failed." >> ${HOME}/.dist_setup_log.tmp
+"echo" "" >> ${HOME}/.dist_setup_log.tmp
+"echo" "Verify that the current working directory when running dist_source_me is the" >> ${HOME}/.dist_setup_log.tmp
+"echo" "top level directory of a distribution source tree -or- if running the script" >> ${HOME}/.dist_setup_log.tmp
+"echo" "from another location, that the value of the environment variable DIST_BASE_DIR"  >> ${HOME}/.dist_setup_log.tmp
+"echo" "contains the full path of the top-level directory of a distribution source tree AND has" >> ${HOME}/.dist_setup_log.tmp
+"echo" "been made available (exported) to child processes of your current shell." >> ${HOME}/.dist_setup_log.tmp
+"echo" "" >> ${HOME}/.dist_setup_log.tmp
 
 
 
@@ -54,7 +54,7 @@ echo "" >> ${HOME}/.dist_setup_log.tmp
 # file existence errors under tcsh in the event the 
 # dist_gen_env script is unable to run.
 #---------------------------------------------------------
-touch ${HOME}/.dist_env_setup.tmp
+"touch" ${HOME}/.dist_env_setup.tmp
 
 
 
@@ -67,7 +67,7 @@ touch ${HOME}/.dist_env_setup.tmp
 # variable to locate a particular distribution top level
 # directory.
 #----------------------------------------------------------
-(sh ./util/dist_gen_env) >& /dev/null || (sh /${DIST_BASE_DIR}/util/dist_gen_env) >& /dev/null || false
+("sh" ./util/dist_gen_env) >& /dev/null || (sh /${DIST_BASE_DIR}/util/dist_gen_env) >& /dev/null || false
 
 
 
@@ -81,12 +81,12 @@ source ${HOME}/.dist_env_setup.tmp
 #----------------------------------------------------------
 # Print status generated by the first step
 #----------------------------------------------------------
-more ${HOME}/.dist_setup_log.tmp
+"more" ${HOME}/.dist_setup_log.tmp
 
 
 
 #----------------------------------------------------------
 # Clean up
 #----------------------------------------------------------
-(rm ${HOME}/.dist_env_setup.tmp) >& /dev/null
+("rm" ${HOME}/.dist_env_setup.tmp) >& /dev/null
 
