Error-checking and documentation adjustments

diff --git a/do_release b/do_release
--- a/do_release
+++ b/do_release
@@ -35,8 +35,12 @@
 #          -vms           Prepare release for transfer to VMS_alpha
 #          -win           Automatic windows builds not yet operational
 #          -nobs          Suppress periodic build-status messages
-#          -ntly          Will run as a nightly build, rotating the library
+#          -ntly          Run a nightly build, rotating the library
 #                          links after completion.
+#          -devel         Run a DEVEL build, rotate release and apply 
+#                          CVS tag.
+#          -curr          Run a CURRENT build, rotate release and apply 
+#                          _special_ CVS tag.
 #          
 #         variables:
 #           REL=<release_name>  Specify a specific CESR release
@@ -65,6 +69,9 @@
 # $Id$
 #
 # $Log$
+# Revision 1.21  2006/09/15 21:33:17  cesrulib
+# Error-checking and documentation adjustments
+#
 # Revision 1.20  2006/09/14 18:42:04  cesrulib
 # Tweaked error checking for rotation
 #
@@ -111,6 +118,8 @@ myprint_help () {
     echo "   -win                Remote exec of Windows build not yet operational"
     echo "   -nobs               Suppress periodic build-status messages."
     echo "   -ntly               Nightly build, rotate library links when done"
+    echo "   -devel              Run a DEVEL build, rotate release and apply CVS tag."
+    echo "   -curr               Run a CURRENT build, rotate release and apply special CVS tag."
     echo ""
     echo "Variable definitions:"
     echo "   REL=<release_name>  Specify a custom CESR release name"
@@ -172,7 +181,9 @@ DO_CHECKOUT="do_checkout"
 DO_BUILD="do_build"
 DO_DUMP=0
 SHOW_STATUS=1
-NIGHTLY=0
+CURRENT_BUILD=0
+DEVEL_BUILD=0
+NIGHTLY_BUILD=0
 GMAKE_OVERRIDE=0
 UTIL_OVERRIDE=0
 use_cesr_bin=/home/cesrulib/bin
@@ -231,7 +242,9 @@ do arg_list="${arg_list} ${i}";
      "-vms"     ) VMS=1; KINIT_CHECK=1;;
      "-win"     ) WIN=1; KINIT_CHECK=1;;
      "-nobs"    ) SHOW_STATUS=0 ;;
-     "-ntly"    ) NIGHTLY=1;;
+     "-ntly"    ) NIGHTLY_BUILD=1;;
+     "-devel"   ) DEVEL_BUILD=1;;
+     "-curr"    ) CURRENT_BUILD=1;;
      TAG=*      ) REL_TAG=`echo $i|cut -d= -f2`;;
      PKG=*      ) PKG=`echo $i|cut -d= -f2`;;
      REL=*      ) REL=`echo $i|cut -d= -f2`;;
@@ -253,8 +266,12 @@ echo ""
 # Obtain a Kerberos V ticket to enable krsh builds on remote hosts
 #################################
 
+kdestroy
 kinit -k -t /etc/cesrulib-keytab cesrulib/lnx209.lns.cornell.edu
-
+if ( [ ${?} -ne 0 ] ) then
+    echo "Could not obtain Kerberos credentials, exiting with error code: ${?}"
+    exit ${?}
+fi
 #Have you run kinit?
 #if ( [ ${KINIT_CHECK} = 1 ] ) then
 #    TERMINAL01=`tty`
@@ -376,7 +393,7 @@ if ( [ $DO_DUMP -eq 1 ] ) then
     echo "BIN_DIR           = ${BIN_DIR}"
     echo "KINIT_CHECK       = ${KINIT_CHECK}"
     echo "SHOW_STATUS       = ${SHOW_STATUS}"
-    echo "NIGHTLY           = ${NIGHTLY}"
+    echo "NIGHTLY_BUILD     = ${NIGHTLY_BUILD}"
 fi
 
 # Print the CESR environment variables
@@ -495,8 +512,15 @@ fi
 
 ###################################################
 # Loop and check build status on all platforms
-###################################################
-max_loops=720
+##################################################################
+# Status value key:    (Double check these values and descriptions)
+#   -1 : currently building on designated host
+#   -2 : build initiated, awating release checkout etc.
+#    0 : build complete
+# +INT : Error code percolated up from some sub-script or command
+##################################################################
+#max_loops=720  #~12 hours worth of looping
+max_loops=480   #~8  hours worth
 sleep_seconds=60
 
 loop=0
@@ -590,9 +614,19 @@ while ( [ $loop -le $max_loops ] && [ $loop_done -eq 0 ] ); do
 done
 
 #------------------------------------------------------
-# If all build jobs complete successfully, tag release 
+# If all build jobs complete successfully, and this is 
+# a DEVEL build, tag release.
+# If this is a CURRENT build -- make tag special
 # NOTE:  Not yet enabled
 #------------------------------------------------------
+if ( [ $loop -lt $max_loops -a $job_status -eq 0 -a $DO_TAG_RELEASE -eq 1 ] ) then
+    if ( [ ${DEVEL_RELEASE} -eq 1 ] ) then
+        tag_release -REL_NAME -TAG_NAME  ## what tag format should this use?
+    fi
+    if ( [ ${CURRENT_RELEASE} -eq 1 ] ) then
+        tag_release REL=${REL_NAME} TAG=${TAG_NAME} ## flag for 'special' tag?
+    fi
+fi
 
 #------------------------
 # Print status summary
@@ -608,14 +642,19 @@ else
 fi
 
 ####################################################
-# If this is a nightly build, has completed
-# without errors, and has not completed by timing
-# out, call the rotate_release script using 
-# appropriate arguments.
+# If this is a nightly build, has not timed out,
+# and has completed without errors, call the 
+# rotate_release script using appropriate arguments.
 ####################################################
-if ( [ $NIGHTLY -eq 1 ] && [ $job_status -eq 0 ] && [ $loop -lt $max_loops ] ) then
+if ( [ $NIGHTLY_BUILD -eq 1 ] && [ $job_status -eq 0 ] && [ $loop -lt $max_loops ] ) then
     /home/cesrulib/bin/util/rotate_release -nightly ${REL_NAME}
+else 
+    echo "ERROR: Not rotating release due to build errors or timeout!"
 fi
 
+#####################################################
+# Do not to leave valid KRB credentials laying about.
+#####################################################
+kdestroy
 
 exit
